openapi: 3.0.0
info:
  title: API сервиса проверки контрагентов
  description: API для автоматической проверки и оценки надежности юридических лиц в Республике Беларусь
  version: 1.0.0
servers:
  - url: /api
    description: API сервера

paths:
  /check.php:
    post:
      summary: Проверка контрагента
      description: Выполняет проверку контрагента по УНП
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                unp:
                  type: string
                  description: УНП контрагента
                  example: "100123456"
      responses:
        '200':
          description: Успешная проверка
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      status:
                        type: string
                      rating:
                        type: number
        '400':
          description: Некорректный запрос
        '404':
          description: Контрагент не найден

  /reports.php:
    get:
      summary: Получение списка отчетов
      description: Возвращает список сохраненных отчетов
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Номер страницы
        - in: query
          name: limit
          schema:
            type: integer
          description: Количество записей на странице
      responses:
        '200':
          description: Список отчетов
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  reports:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        unp:
                          type: string
                        date:
                          type: string
                          format: date-time
                        status:
                          type: string

  /export_pdf.php:
    get:
      summary: Экспорт отчета в PDF
      description: Генерирует PDF-отчет по указанному ID
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
          description: ID отчета
      responses:
        '200':
          description: PDF файл
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: Отчет не найден

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [] 